### ISSUE TITLE
History

### ISSUE THREAD

**Issue by ignatandrei** [jenkinsci/lockable-resources-plugin#43] opened 2017-01-17 11:14 UTC
Please make possible to get the history of usage of a lockable resource

**Comment by oubre** [comment] 2018-09-12 19:14
I would also find this feature very helpful. We've had issues where one of the resources starts having issues, and it's very hard to track down problems of this type. If I could see that all builds using a particular locked resource were failing, that would make identifying such problems simple.

**Comment by jimklimov** [comment] 2022-02-06 18:24
Seems duplicated by #141 (posted later but in more detail)

**Comment by jimklimov** [comment] 2022-02-06 18:26
Closing to avoid noise in issue tracker, but currently the problem is not solved yet.

**Closed by jimklimov** 2022-02-06 18:26 UTC
Labels: lock queue priority and visibility, ui, extended properties
