### ISSUE TITLE
What happens if "Reserved by" of a resource is set while it's locked?

### ISSUE THREAD

**Issue by dhs-rec** [jenkinsci/lockable-resources-plugin#288] opened 2022-02-02 09:07 UTC
### Describe your use-case which is not covered by existing documentation.

Sometimes I need to temp. reserve a resource from a pool. The documentation doesn't tell what happens to a build that holds a resource if the "Reserved by" field is filled and the configuration saved during this time.

**Comment by jimklimov** [comment] 2022-02-06 12:26
A documentation PR would be welcome, then :)

In practical terms, this is something our jobs do and that led to the "steal lock"/"reassign user" buttons that was in our private builds and a dangling PR #144 for some time, until merged for 2.14 release.

We use this for something ideologically out of scope of the lockable resources workflow, possibly opposing the ideology (see discussion in #64) but addressing our practical need - adding a way to "leak resources" so that we can do post-mortems on a tested system without letting it be recycled by another build when a test ends. If developers reproduced or just saw a failure while a test job runs, they can steal the resources involved to keep them afloat after that job ends, and investigate the issue. Makes sense when it can take hours to reproduce. To avoid unlimited leaks, someone or something (further jobs) should release these resources eventually.

The `lock()` step takes care of assigning a Build object to a resource; the `reserve()` actions instead assign a String object to another variable. A resource technically can be both locked and reserved at the same time, and is only available for taking if it is neither locked nor reserved (#279 at least addressed a bug about transitions in this area).

**Comment by dhs-rec** [comment] 2022-02-07 07:19
So, can I safely set `Reserved by` while a running build is holding a resource, w/o harming that build?

**Comment by mPokornyETM** [comment] 2022-11-01 17:18
You mean set it in the configuration page? Because in the overview page it should be not possible to see action 'reserve' in case resource is locked by build. Of course it can happen, when you don't refresh the page.  In that case it is handled on server side and it will be not reserved for you. 

From my POV we should remove the field 'reserved by' from configure page, because it makes no sense and it makes only troubles (ex in configuration as code, or reserved by unknown user).

When you agree, I will propose to create new documentation page about possible actions and create new issue to remove this property from configuration page. And we can discuss it later.

**Closed** 2022-11-11 23:16 UTC
Labels: API interactions, documentation
