### ISSUE TITLE
inversePrecedence: true not working

### ISSUE THREAD

**Issue by christian-baltazar-motork** [jenkinsci/lockable-resources-plugin#560] opened 2023-09-16 10:42 UTC
### Jenkins and plugins versions report

Jenkins: 2.414.1
OS: Linux - 5.15.49-linuxkit-pr
Java: 11.0.20 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
bootstrap5-api:5.3.0-1
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-timeout:1.31
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.1
cloudbees-folder:6.848.ve3b_fd7839a_81
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
credentials:1271.v54b_1c2c6388a_
credentials-binding:636.v55f1275c7b_27
dashboard-view:2.495.v07e81500c3f2
data-tables-api:1.13.5-1
display-url-api:2.3.9
durable-task:523.va_a_22cf15d5e0
echarts-api:5.4.0-5
email-ext:2.101
font-awesome-api:6.4.0-2
git:5.2.0
git-client:4.5.0
github:1.37.3
github-api:1.314-431.v78d72a_3fe4c3
github-branch-source:1740.v51d5810e9e8c
gradle:2.8.2
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jjwt-api:0.11.5-77.v646c772fddb_0
jquery3-api:3.7.0-1
junit:1217.v4297208a_a_b_ce
ldap:694.vc02a_69c9787f
lockable-resources:1185.v0c528656ce04
mailer:463.vedf8358e006b_
matrix-auth:3.2
matrix-project:808.v5a_b_5f56d6966
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pam-auth:1.10
pipeline-build-step:505.v5f0844d8d126
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.3.0
resource-disposer:0.23
scm-api:676.v886669a_199a_a_
script-security:1275.v23895f409fb_d
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
structs:325.vcb_307d2a_2782
throttle-concurrents:2.14
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1281.vca_5fddb_3fceb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3787.v8f5dcd14a_fa_c
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1346.v180a_63f40267
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45

### What Operating System are you using (both controller, and any agents involved in the problem)?

Official jenkins docker image from docker hub jenkins/jenkins:lts-jdk11 
Controller: 2.414.1 

### Reproduction steps

Using the lockable resources plugin from one pipeline like 
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                lock(resource: "wsk_release_token", inversePrecedence: false){
                    echo 'Hello World'
                    sleep(60)    
                    echo "Bye..."
                }
            }
        }
    }
}
```

and another one like 
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                lock(resource: "wsk_release_token", inversePrecedence: true){
                    echo 'Help!!!'
                    sleep(30)
                    echo "Ok"
                }
            }
        }
    }
}
```

then running several jobs of the first one, and one of the second one in the middle...

### Expected Results

The second job should jump into the current queue taking the next available slot right after the resource if free and run

### Actual Results

The second job gets added to the end of the queue every time as any other job using the resource

**Comment by mPokornyETM** [comment] 2023-09-23 13:35
@christian-baltazar-motork thx for reporting. I found this issue too. I tr yto refactor this plugin in last weeks and can confirm, that the inverse precedense is done in wrong way.
I will try to fix it and also implement kind of queue priority. But first I need to fix all the concurent exceptions and performance issues.

**Comment by PayBas** [comment] 2023-10-05 07:55
Ah so that's why my stuff keeps breaking!

Do we know when this regression was introduced? So I can revert to the last working version before that.

**Comment by mPokornyETM** [comment] 2023-10-05 08:02
> Ah so that's why my stuff keeps breaking!
> 
> Do we know when this regression was introduced? So I can revert to the last working version before that.

I have no ideay, I found it until refactoring. Just because of thinkig 'how the logic works and it ca nnot be correct'. How important is this fix for you? I can try to fix in next week (hopefully)

**Comment by PayBas** [comment] 2023-10-05 08:34
Very important unfortunately.

We basically use this plugin as follows:
1. Each resource represents a testing environment
2. Each build+test job locks a resource based on a `label` with `resourceSelectStrategy: 'random'`
3. As soon as a lock is obtained, we trigger a "clean" job and pass the lock `variable`
4. This "clean" job tries to lock the exact resource as well using `resource` instead of `label`, but with `inversePrecedence: true`
5. As soon as the build+test job releases the lock, the "clean" job takes over and cleans/resets the resource.
6. Any test jobs waiting for a resource will have to wait until a cleaned resource is available. Even if they are higher in the queue than the "clean" job.

As it stands now, test jobs can get "dirty" resources, which breaks everything ;)

**Comment by mPokornyETM** [comment] 2023-10-05 09:31
I see. Let me try to fix it. But, first next week.

One hack maybe?! You can start your child job and wait for execution, in the parrent job as well. This may eliminate your problem now.

**Comment by PayBas** [comment] 2023-10-05 13:52
Further testing appears to show that the current behavior may actually be _inverted_.
So having `inversePrecedence: true` as the _default_ and having a single job with `inversePrecedence: false` seems to result in the `inversePrecedence: false` job bypassing the rest.

This is exactly the opposite behavior of what I would expect.

**Comment by mPokornyETM** [comment] 2023-10-05 14:12
I try to explain current implementation

when you call the function lock(..., inversePrecedense ; true);

1. nothing locked --> you winn

2. currently locked -> added in queue

seem to be fine, but ..
use it in exact this combination
jobName | resource | inversePrecedens
j1             | r1           | true
j2             | r1           | false
j3             | r1           | false

when job j1 released the resource r1 we became a 'callback' and try to get next possible queued item.
The marker how to search (from top_to_down or down_to_top) is in the callabck, In this case from j1 and it means  inversePrecedens:true. that means the job j3 will winns. And that the issue. It shall be remeber in the queu-item self. Or better when the item is added into queue it shall be sorted at the moment, and not just push() ...

So I know, where is the issue, and also how to solve. But the changes is deep in code and might provide many side effects. Therefore I need to extend also tests to be sure it works as expected.
Therefore I need litle bit more time, then one late-summer night ;-)

**Comment by PayBas** [comment] 2023-10-27 15:29
@mPokornyETM any update on this?

**Comment by mPokornyETM** [comment] 2023-11-24 15:51
@PayBas I need to merge this changes first #558
otherwise I will get merge conflict again and lost again many of my time by resolving it.
I will try to bring all the changes form my own Jenkins instance into plugin before end of 2023. Not sure currently overhelmed by all the projects and here are missed contributors. Therefore it takes very long to review simple changes.
How important it is for you? There are few ways, how to force any whisches.

**Comment by PayBas** [comment] 2023-11-25 13:55
@mPokornyETM obviously you should work in the order that suits you best. I'm in no position to make demands on volunteers.
Any work being done to address the issue is highly appreciated, no matter the time-frame.

If you had said: "maybe I'll fix it somewhere in 2024", I might have been tempted to fork the plugin and try to fix the issue myself (and submit a PR). But getting familiar with the internal workings of individual plugins is always very time-consuming (for me at least).

**Comment by mPokornyETM** [comment] 2023-11-26 20:42
@PayBas  I will propose a deal, review / test PRs, provide documentation, what ever may helps to improve velocity here. And I will try to fix it. Any kind of help is welcome.

Zhere are 2 things.
1. Fux this bug as well
2. Provide functionality to re-order queue by user (groovy script). In that case you can choise which item in queue has bigger priority. Because inverse precedence might be in many cases too less.

I know, there are 2 different topics, but it must be change the same code part as well.

**Comment by PayBas** [comment] 2023-11-28 12:10
Testing is something I can definitely do.
PR reviewing might be difficult since I'm not familiar with the code, but I can always try.

**Comment by mPokornyETM** [comment] 2024-01-17 21:33
OK, I think I will find the time now. It is probably the next top / hot topic here

**Comment by PayBas** [comment] 2024-01-23 00:15
It's certainly still a hot topic for us.

To be clear: this is still the desired behavior right? (assuming **all jobs run 10min**)

start time | job | resource | inversePrecedence
---|---|---|---
00:01 | j1 | r1 | false
00:02 | j2 | r1 | false
00:03 | j3 | r1 | **true**
00:04 | j4 | r1 | false
00:05 | j5 | r1 | **true**
00:06 | j6 | r1 | false

Scenario 1:
`Lock order: j1 -> j3 -> j5 -> j2 -> j4 -> j6`
or
Scenario 2:
`Lock order: j1 -> j5 -> j3 -> j2 -> j4 -> j6`

I think simply pushing lock-requests with `inversePrecedence` to the top of the queue will result in scenario 2. Ideally I think scenario 1 would be more "fair", but it would probably require a different kind of queuing.

At that point it might be a logical next step to simply replace  `inversePrecedence` with weight/priority integers ranging 0-9.

But anything is better than how it works (or doesn't work) right now ;).

**Comment by mPokornyETM** [comment] 2024-01-23 07:42
great table,  my current implementation (in the feature branch) works as your **scenario 2**
Scenario 1 is more is fair, but again will leads to missleadings. I hope you now waht I mean.

But I will also add support for priority like

lock(resource : 'ABC';, priority : 100)  {
 ...
}

in case you use **inversePrecedence** priority will be ignored (and still winds scenario 2)

I also try to add a way to change the queue order direct in the lockable-resources page. So "every" one can decide, which scope (build, stage ...) has bigger priority and reorder it manually. (I am still not sure who shall have the permission to do the action)


when you agree the idea, it comming soon ... ;-)

**Comment by PayBas** [comment] 2024-01-23 12:24
I think allowing manual manipulation of the queue is a nice feature, but definitely not as important as fixing the `inversePrecedence` behavior.
One is a completely new feature, whereas the other is a fix for broken current behavior.

Besides, it would require thorough testing and it might have security/permission implications as you said.

**Comment by mPokornyETM** [comment] 2024-01-23 13:25
in that case I will create 2 separate PRs. One with the fix and other one with priority.
I think the fix might be released this week. we will see.

**Comment by mPokornyETM** [comment] 2024-02-22 13:19
not finished jet, breaks by other important things, sorry. maybe next week ;-) I hope

**Comment by mPokornyETM** [comment] 2024-03-04 00:19
@PayBas @flyingdutchmen2  somebody to check / test this changes ;-)

#632

**Comment by flyingdutchmen2** [comment] 2024-03-04 13:59
@mPokornyETM  im on it for testing
artifact: https://repo.jenkins-ci.org/incrementals/org/6wind/jenkins/lockable-resources/1268.vda_7a_dc31a_d0a_/lockable-resources-1268.vda_7a_dc31a_d0a_.hpi

**Comment by mPokornyETM** [comment] 2024-03-04 20:46
@flyingdutchmen2 tzx

**Comment by flyingdutchmen2** [comment] 2024-03-05 10:19
tested with inversePrecedence true/false

Jenkins version: 2.440.1
Lockable Resources plugin version: 1268.vda_7a_dc31a_d0a_

| Start time | Job Name	| Job Nr. |	Resource      | inversePrecedence |
|:---------- |:-------- |:------- |:------------- |:----------------- |
| 00:01	     | Sample-A	| 106     | test-resource | false |
| 00:02	     | Sample-A	| 107	  | test-resource | false |
| 00:03	     | Sample-B	| 47	  | test-resource | **true** |
| 00:04	     | Sample-A	| 108	  | test-resource | false |
| 00:05      | Sample-B	| 48	  | test-resource | **true** |

lock-order: 106 -> 48 -> 47 -> 107 -> 108

seems Ok to me

**Closed** 2024-03-19 21:28 UTC
Labels: bug, lock queue priority and visibility, skipIfLocked, Need test
