### ISSUE TITLE
Reader/writer locks

### ISSUE THREAD

**Issue by harlowja** [jenkinsci/lockable-resources-plugin#196] opened 2020-04-20 16:51 UTC
We have a jenkins job that updates an apt-repo we have internally (the writer) and we have various other jenkins jobs that read from that repo (readers) doing things like docker builds, apt-get updates and installs...

We'd really love the ability to have multiple lock readers and one lock writer be a possibility. Right now it appears we can only have writer locks (but seeing as java has a https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReadWriteLock.html maybe it can be used?) but it would be very useful for our case (and maybe others) to have this ability.

**Comment by harlowja** [comment] 2020-04-20 16:57
https://github.com/jenkinsci/lockable-resources-plugin/issues/105 seems related.

**Comment by TobiX** [comment] 2020-04-21 06:41
Closing as a duplicate of #105

**Closed by TobiX** 2020-04-21 06:41 UTC
Labels: duplicate
