### ISSUE TITLE
Rememering search query stopped working

### ISSUE THREAD

**Issue by yandemontreal** [jenkinsci/lockable-resources-plugin#569] opened 2023-10-10 23:40 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.401.3
OS: Linux - 5.4.0-80-generic
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
aws-credentials:218.v1b_e9466ec5da_
aws-java-sdk:1.12.529-406.vdeff15e5817d
aws-java-sdk-cloudformation:1.12.529-406.vdeff15e5817d
aws-java-sdk-codebuild:1.12.529-406.vdeff15e5817d
aws-java-sdk-ec2:1.12.529-406.vdeff15e5817d
aws-java-sdk-ecr:1.12.529-406.vdeff15e5817d
aws-java-sdk-ecs:1.12.529-406.vdeff15e5817d
aws-java-sdk-efs:1.12.529-406.vdeff15e5817d
aws-java-sdk-elasticbeanstalk:1.12.529-406.vdeff15e5817d
aws-java-sdk-iam:1.12.529-406.vdeff15e5817d
aws-java-sdk-kinesis:1.12.529-406.vdeff15e5817d
aws-java-sdk-logs:1.12.529-406.vdeff15e5817d
aws-java-sdk-minimal:1.12.529-406.vdeff15e5817d
aws-java-sdk-secretsmanager:1.12.529-406.vdeff15e5817d
aws-java-sdk-sns:1.12.529-406.vdeff15e5817d
aws-java-sdk-sqs:1.12.529-406.vdeff15e5817d
aws-java-sdk-ssm:1.12.529-406.vdeff15e5817d
badge:1.9.1
bitbucket-pullrequests-filter:13.vda_de92e841b_b_
blueocean:1.27.8
blueocean-bitbucket-pipeline:1.27.8
blueocean-commons:1.27.8
blueocean-config:1.27.8
blueocean-core-js:1.27.8
blueocean-dashboard:1.27.8
blueocean-display-url:2.4.2
blueocean-events:1.27.8
blueocean-git-pipeline:1.27.8
blueocean-github-pipeline:1.27.8
blueocean-i18n:1.27.8
blueocean-jira:1.27.8
blueocean-jwt:1.27.8
blueocean-personalization:1.27.8
blueocean-pipeline-api-impl:1.27.8
blueocean-pipeline-editor:1.27.8
blueocean-pipeline-scm-api:1.27.8
blueocean-rest:1.27.8
blueocean-rest-impl:1.27.8
blueocean-web:1.27.8
bootstrap5-api:5.3.2-1
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-failure-analyzer:2.4.2
build-monitor-plugin:1.14-744.v35fd6fa_a_26b_2
build-timeout:1.31
build-user-vars-plugin:1.9
buildtriggerbadge:251.vdf6ef853f3f5
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
claim:516.v36293563731d
cloudbees-bitbucket-branch-source:845.v27a_d5823911b_
cloudbees-folder:6.848.ve3b_fd7839a_81
cobertura:1.17
code-coverage-api:4.7.0
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
configuration-as-code:1700.v6f448841296e
copyartifact:722.v0662a_9b_e22a_c
credentials:1271.v54b_1c2c6388a_
credentials-binding:636.v55f1275c7b_27
data-tables-api:1.13.6-4
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
durable-task:523.va_a_22cf15d5e0
ec2:1.69.spotFix-SNAPSHOT (private)
ec2-fleet:3.0.1
echarts-api:5.4.0-6
editable-choice:71.v02a291ebbe45
email-ext:2.102
external-workspace-manager:1.3.1
extra-columns:1.26
favorite:2.4.3
file-operations:131.v32b_e7824fe95
font-awesome-api:6.4.2-1
forensics-api:2.3.0
generic-webhook-trigger:1.87.0
git:5.2.0
git-client:4.5.0
github:1.37.3
github-api:1.316-451.v15738eef3414
github-branch-source:1741.va_3028eb_9fd21
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.32
http_request:1.18
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-8
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.8
jersey2-api:2.40-1
jfrog:1.5.0
jira:3.11
jjwt-api:0.11.5-77.v646c772fddb_0
job-restrictions:0.8
jquery3-api:3.7.1-1
junit:1240.vf9529b_881428
ldap:701.vf8619de9160a_
lockable-resources:1185.v0c528656ce04
mailer:463.vedf8358e006b_
matrix-project:808.v5a_b_5f56d6966
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
monitoring:1.95.0
multibranch-build-regex-filter-extension:v0.0.5-alpha
node-iterator-api:49.v58a_8b_35f8363
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
parameterized-scheduler:255.v73827fcdf618
pipeline-build-step:505.v5f0844d8d126
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.4.0
prism-api:1.29.0-8
publish-over:0.22
publish-over-dropbox:1.3.2
pubsub-light:1.17
resource-disposer:0.23
robot:3.4.0
role-strategy:689.v731678c3e0eb_
scm-api:676.v886669a_199a_a_
scm-filter-branch-pr:77.vf2b_85e1970d5
scoring-load-balancer:59.vf791549fa_989
script-security:1275.v23895f409fb_d
simple-queue:1.4.3
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.16
sse-gateway:1.26
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.249.v2dc2ea_416e33
stashNotifier:1.439.v202358346a_7d
structs:325.vcb_307d2a_2782
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
view-job-filters:369.ve0513a_a_f5524
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3793.v65dec41c3a_c3
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1326.ve643e00e9220
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker image jenkins/jenkins:lts on Ubuntu 22

### Reproduction steps

Go to Lockable Resource
Enter a search query and/or change number of items per page
Reload page
Observe that neither search query, nor number of entries per page are remembered

### Expected Results

Search query text and number of entries per page should be recalled and filled according to the last input.

### Actual Results

Search parameters are reset to their default value (10 entries per page, blank search box) every time the page is reloaded.

### Anything else?

This has happened while rebuilding Jenkins docker image (off of jenkins/jenkins:lts). In this new image, the same version of Jenkins was used, but all the plugins were updated to their latest version. It's likely that a dependent plugin has caused this problem.

**Comment by PayBas** [comment] 2023-10-12 10:01
Looks like duplicate of https://github.com/jenkinsci/lockable-resources-plugin/issues/567

**Closed** 2023-10-12 12:38 UTC
