### ISSUE TITLE
Since 2.0, resource locks are broken in multi configuration projects

### ISSUE THREAD

**Issue by Ext3h** [jenkinsci/lockable-resources-plugin#54] opened 2017-04-26 08:11 UTC
See https://issues.jenkins-ci.org/browse/JENKINS-43574

For multi configurations projects, lockable resources no longer behave as they should.

In my setup, I have a single lockable resource, which is locked by name, and a single multi configuration job with 2 different configurations executing on different slave nodes, locking that resource.
The parent job itself is executed on a 3rd slave node, by random scheduling choice.

When the parent project starts, all child jobs are enqueued and the first child job starts, while the other job is enqueued. The web interface shows, that the second job would still be waiting on the resource, and the resource itself shows up as "queued" state (not locked!).

After a short delay, the second job also starts, in parallel with the other child job requiring exactly the same resource. The resource now shows as "free", despite both jobs still running.

Both child jobs have the following line in their log:

    [lockable-resources] acquired lock on []

As you can see, no resource has actually been locked.

Downgrading to 1.11.2 resolves the issue for me, so the breaking change must have been introduced with any of the changes in 2.0.

Nothing else in an of the jenkins logs, hinting at what could possibly have gone wrong.

**Comment by debfx** [comment] 2017-04-27 12:10
Downgrading only helps if you save the job afterwards.

More specifically the issue is present when the job config looks like this:
```
    <org.jenkins.plugins.lockableresources.RequiredResourcesProperty plugin="lockable-resources@1.11.2">
      <resourceNames>ResX ResY</resourceNames>
      <resourceNamesVar></resourceNamesVar>
      <resourceNumber></resourceNumber>
      <labelName></labelName>
    </org.jenkins.plugins.lockableresources.RequiredResourcesProperty>
```

But this works fine:
```
    <org.jenkins.plugins.lockableresources.RequiredResourcesProperty plugin="lockable-resources@1.11.2">
      <resourceNames>ResX ResY</resourceNames>
    </org.jenkins.plugins.lockableresources.RequiredResourcesProperty>
```

**Comment by shlomibe** [comment] 2017-06-28 04:41
I have the same problem. Removing the tags seems to do the trick.
Thanks!

**Comment by sirosen** [comment] 2017-09-20 13:51
Is there any activity on this issue? GitHub doesn't show any referent PRs.

I also see this bug with two entirely distinct freestyle jobs locking on the same resource.

I'm currently living with the fact that I have to carefully remember to _not_ upgrade this plugin because it will break half of our builds.

**Comment by TobiX** [comment] 2019-10-12 22:33
This should have been fixed with #89 (?) - so since 2.2 (March 2018) this should work as expected...

**Comment by sirosen** [comment] 2019-10-14 17:20
IIRC, we tested the 2.2 release when it came out and confirmed that it fixed the issue for us. At the very least, we upgraded and nobody in our team has complained in the past year.

We've also stopped relying on this plugin so much for our builds, so it's possible that we wouldn't catch it in our organization if it were still happening in rare cases.

**Comment by TobiX** [comment] 2019-10-14 20:45
@sirosen Thanks for the feedback, I'm closing this issue then - Feel free to reopen if the issue reappears.

**Closed by TobiX** 2019-10-14 20:45 UTC
